### ISSUE TITLE
Issues with firefox?

### ISSUE THREAD

**Issue by reox** [Kipjr/cookieconsent#14]
I have a weird issue with this plugin and firefox 116: In the list of plugins, the plugin is always hidden. However, with chrome it works fine.
Is this a known issue or simply a problem of my specific installation?

I use piwigo 13.8.0

**Comment by Kipjr** [comment]
A clean install on Chrome 115:
![image](https://github.com/Kipjr/cookieconsent/assets/12066560/944a286c-a8f5-4ac3-b8c0-f79c16e3b205)

A clean install on Firefox  115.0.2:
![image](https://github.com/Kipjr/cookieconsent/assets/12066560/00137599-a524-4113-8575-591868e2d8d8)

A clean install on Firefox 116.0.3:
![image](https://github.com/Kipjr/cookieconsent/assets/12066560/838dded5-fc44-45a4-b91d-aff4825c2487)

In Admin/Plugins it is visible when I activate it.
![image](https://github.com/Kipjr/cookieconsent/assets/12066560/202e3d1e-8d84-4eba-83e6-4e9d2afc2081)

It is hidden after install because you need to activate it afterwards as you might want to change the settings before showing it to your audience:
![image](https://github.com/Kipjr/cookieconsent/assets/12066560/3848f006-fddb-471d-b274-87ab14dfe6bd)

**Comment by reox** [comment]
This is how firefox looks for me:
![image](https://github.com/Kipjr/cookieconsent/assets/431045/45c1b335-d9cb-43a8-a798-b74d95420c4a)

in contrast to chrome:
![image](https://github.com/Kipjr/cookieconsent/assets/431045/ac79db42-5b89-4f37-8ffe-eb5c55f2b661)


But I found out what is interfering... 🤦 
I use the "I still don't care about cookies" addon in firefox, which simply removes the div with the id "cookieconsent" from the view:
![image](https://github.com/Kipjr/cookieconsent/assets/431045/359f9ef3-2a6f-4a5b-80ed-1c467972423d)

Funny enough - it does not remove the actual cookie banner from the site.

But okay, found the cause and added my site to the whitelist.
